layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name (repos that should be excluded from the listing)

social_media:
  linkedin: landonpatmore
  stackoverflow: 6562312
  twitter: landon_patmore
  youtube: channel/UC7n_qTzSqOfhmQ0mhCeuSqA