layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name (repos that should be excluded from the listing)

social_media:
  linkedin: landonpatmore
  stackoverflow: 6562312
  twitter: landon_patmore
  youtube: channel/UC7n_qTzSqOfhmQ0mhCeuSqA

topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
